version: "3.8"

services:
    adk-web:
        build:
            context: ./adk-web
            dockerfile: Dockerfile
            x-bake:
                platforms:
                    - linux/amd64
                    - linux/arm64
        image: asia-south1-docker.pkg.dev/ai-analyst-for-startup-eval/ai-analyst-ui/adk-web:latest
        container_name: adk-web
        ports:
            - "8085:80"
        restart: unless-stopped
    ai-analyst-agent:
        build:
            context: .
            dockerfile: agents/Dockerfile
            x-bake:
                platforms:
                    - linux/amd64
                    - linux/arm64
        container_name: ai-analyst-agent
        image: asia-south1-docker.pkg.dev/ai-analyst-for-startup-eval/ai-analyst/ai-analyst-ai-analyst-agent:latest
        working_dir: /app
        volumes:
            - ./agents:/app/agents:ro
            - ./requirements.txt:/app/requirements.txt:ro
            - ./ai-analyst-for-startup-eval-40d9cd5e982e.json:/app/credentials.json:ro
        ports:
            - "8080:8080"
        environment:
            - PORT=8080
            - PYTHONUNBUFFERED=1
            - LOG_LEVEL=INFO
            - GOOGLE_GENAI_USE_VERTEXAI=TRUE
            - GOOGLE_CLOUD_PROJECT=ai-analyst-for-startup-eval
            - GOOGLE_CLOUD_LOCATION=europe-west3
            - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
        restart: unless-stopped
        command: CMD ["adk", "web", "--host", "0.0.0.0", "--port", "8080", "agents", "--allow_origins", "*"]
